import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { RootStyleRegistry } from "./RootStyleRegistry";

export const metadata = {
  title: "Frontend Sample",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-[#efefef]">
        <div className="m-auto h-screen max-w-[500px] overflow-auto bg-white">
          <RootStyleRegistry>{children}</RootStyleRegistry>
        </div>
      </body>
    </html>
  );
}
